// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXYDxW8cIDX7_ncd_G16-3uwfmX34K2cA',
    appId: '1:369575662858:web:2ae091baca8ef1287616f3',
    messagingSenderId: '369575662858',
    projectId: 'auth-demo-f6a33',
    authDomain: 'auth-demo-f6a33.firebaseapp.com',
    storageBucket: 'auth-demo-f6a33.firebasestorage.app',
    measurementId: 'G-KLVWMWB5GC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEHyGqbBBk7TRUk3imL07vZSv5VW8-p7I',
    appId: '1:369575662858:android:37beeac4a5c6d3e27616f3',
    messagingSenderId: '369575662858',
    projectId: 'auth-demo-f6a33',
    storageBucket: 'auth-demo-f6a33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOVP0mGqHbZSemYJy_bjJL7d_L_wgCaBA',
    appId: '1:369575662858:ios:49003373865d7b497616f3',
    messagingSenderId: '369575662858',
    projectId: 'auth-demo-f6a33',
    storageBucket: 'auth-demo-f6a33.firebasestorage.app',
    iosBundleId: 'com.example.demoPhoneGoogleAuth',
  );
}
